---
abstract: 'I2C interface to LSM303DLHC 3 axis magnetometer(compass) and accelerometer using Device::SMBus'
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-LSM303DLHC
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Device::LSM303DLHC:
    file: lib/Device/LSM303DLHC.pm
    version: 0.004
  Device::LSM303DLHC::Accelerometer:
    file: lib/Device/LSM303DLHC/Accelerometer.pm
    version: 0.004
  Device::LSM303DLHC::Compass:
    file: lib/Device/LSM303DLHC/Compass.pm
    version: 0.004
requires:
  Device::SMBus: 0
  Moose: 0
  POSIX: 0
  constant: 0
  integer: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/shantanubhadoria/device-lsm303dlhc/issues
  homepage: https://metacpan.org/release/Device-LSM303DLHC
  repository: git://github.com/shantanubhadoria/device-lsm303dlhc.git
version: 0.004
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
  - 'Shantanu Bhadoria <shantanu@cpan.org>'
